[project]
name = "localmoodle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.12.2",
    "requests>=2.31.0",
    "selenium>=4.12.0",
    "webdriver-manager>=4.0.0",
]
